### ISSUE TITLE
[Refactor] Improve build system

### ISSUE THREAD

**Issue by migueldeoleiros** [migueldeoleiros/turtile#18]

**Comment by PerryWerneck** [comment]
I can implement a meson build system if you agree!

**Comment by migueldeoleiros** [comment]
My original plan was actually using meson, but I struggled with the use of wayland scanner for `xdg-shell-protocol.h` so I stuck with a makefile for now.
If you have some experience with meson I think it should be trivial, all help is welcomed :)

**Comment by PerryWerneck** [comment]
Yes, I'm already packaging another project with embedded turtile using meson, xdg-shell-protocol was a little trick but it's working. I'll fork your project and add a meson build. Just give me some time.
